language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  # setup apt package
  - sudo apt-get update
  - sudo apt-get install g++
  - sudo apt-get install zlib1g-dev
  # build kyotocabinet
  - wget http://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.76.tar.gz
  - tar zxvf kyotocabinet-1.2.76.tar.gz
  - cd kyotocabinet-1.2.76
  - ./configure CXXFLAGS='-mno-avx'
  - make
  - sudo make install
  - cd -
  # build kyototycoon
  - wget http://fallabs.com/kyototycoon/pkg/kyototycoon-0.9.56.tar.gz
  - tar zxvf kyototycoon-0.9.56.tar.gz
  - cd kyototycoon-0.9.56
  - ./configure CXXFLAGS='-mno-avx'
  - sed -i -e "/^#include <kttimeddb.h>$/a \#include <unistd.h>" ./ktdbext.h
  - make
  - sudo make install
  - cd -
  # setup library path
  - sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf.d/libc.conf"
  - sudo ldconfig
  # start kyototycoon
  - /usr/local/bin/ktserver -host localhost -port 1978 -dmn red#type=% blue#type=*

script:
  - npm run lint
  - npm run cover
